name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**

env:
  AZURE_FUNCTIONAPP_NAME: ScottPlotStatsFunctions20240210172317
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/ScottPlotStats.Functions/published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: src/ScottPlotStats.Functions
  TEST_DIRECTORY: src/ScottPlotStats.Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.TEST_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.TEST_DIRECTORY }}" --no-restore
      - name: Test
        env:
          github_token: ${{ secrets.GH_TOKEN }}
        run: dotnet test "${{ env.TEST_DIRECTORY }}" --no-build
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.ScottPlotStatsFunctions20240210172317_A716 }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
